import numpy

In [1]:
import numpy as np

lets initialize arrays and use functions


In [3]:
a = np.array([1,2,3,4,5])
## a = np.array([1,2,3,4,5],dtype='int16')
print(a)                       # 1 d array

[1 2 3 4 5]


In [4]:
b = np.array([[1.0,2.2,3.0,4.4],[3.3,4.1,5.2,7.7]])
print(b)                         # 2 D array

[[1.  2.2 3.  4.4]
 [3.3 4.1 5.2 7.7]]


using some functions

In [7]:
a.ndim       ## used to print dimensions of array

1

In [8]:
b.ndim          ## used to print dimensions of array

2

In [9]:
a.shape

(5,)

In [10]:
b.shape   # to print the shape of array like its dimensions and no of values in each dimension

(2, 4)

In [11]:
a.dtype

dtype('int64')

In [12]:
b.dtype               ## in all if we dont define data tyope it will show 64 but we can define it  as shown above

dtype('float64')

In [13]:
a.itemsize           # as int 32 has 8 bits

8

In [14]:
b.itemsize

8

In [15]:
a.nbytes

40

In [16]:
b.nbytes

64

how to access elements from and array using row and colum

In [20]:
b[1,3]= 6.9
print(b)

[[1.  2.2 3.  4.4]
 [3.3 4.1 5.2 6.9]]


: use to get entire row or column

In [24]:
b[:,0]= 1.1
print(b)

[[1.1 2.2 3.  4.4]
 [1.1 4.1 5.2 6.9]]


In [28]:
b[0,:]=[1.1,2.9,3.1,4.9]
print(b)

[[1.1 2.9 3.1 4.9]
 [1.1 4.1 5.2 6.9]]


3-d array
([[[]]])= 3d
([[]])= 2 d
([])= 1 d



In [29]:
c = np.array([[[1,2],[1,3]],[[1,4],[4,5]]])
print(c)

[[[1 2]
  [1 3]]

 [[1 4]
  [4 5]]]


c[layer,row,column]

In [31]:
c[0,1,1]

np.int64(3)

In [32]:
c[0,1,1]= 4
print(c)

[[[1 2]
  [1 4]]

 [[1 4]
  [4 5]]]


In [34]:
c[:,0,:]  ## print first rows of both layer

array([[1, 2],
       [1, 4]])

In [35]:
c[:,:,0]

array([[1, 1],
       [1, 4]])