Will use some functions to generate arrays

In [8]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [9]:
np.full_like(a,9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [10]:
np.random.rand(5,3,3)

array([[[0.43256836, 0.29688572, 0.29600641],
        [0.02554148, 0.19877557, 0.25153041],
        [0.08477403, 0.86651972, 0.7456167 ]],

       [[0.33972221, 0.48740223, 0.35638368],
        [0.89301133, 0.23620665, 0.2633184 ],
        [0.23830748, 0.51034078, 0.48734335]],

       [[0.04970485, 0.65301951, 0.09100034],
        [0.85534072, 0.19936338, 0.02408636],
        [0.80467583, 0.45781754, 0.07239438]],

       [[0.26103838, 0.40715219, 0.55296536],
        [0.65758123, 0.7025623 , 0.55738129],
        [0.8734998 , 0.01396245, 0.72653236]],

       [[0.96129109, 0.07293813, 0.6807999 ],
        [0.45789871, 0.58850248, 0.85355881],
        [0.86938934, 0.44177412, 0.01905552]]])

In [16]:
np.random.randint(4,7,size=(4,5,5))

array([[[6, 5, 5, 5, 6],
        [6, 4, 4, 6, 5],
        [4, 4, 5, 6, 5],
        [5, 5, 5, 5, 4],
        [6, 6, 5, 6, 4]],

       [[4, 5, 6, 5, 4],
        [4, 5, 6, 5, 6],
        [5, 5, 6, 5, 5],
        [5, 6, 4, 6, 6],
        [6, 5, 5, 6, 5]],

       [[4, 4, 4, 6, 5],
        [5, 4, 4, 4, 6],
        [4, 6, 6, 5, 6],
        [4, 5, 6, 4, 4],
        [5, 5, 5, 4, 4]],

       [[5, 6, 5, 5, 4],
        [5, 6, 6, 6, 6],
        [4, 4, 5, 4, 6],
        [4, 4, 4, 5, 4],
        [4, 4, 6, 6, 4]]])

In [13]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
r1=np.repeat(a,3, axis=0)
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [23]:
b=np.ones((5,5))
c=np.zeros((3,3))
c[1,1]=9
b[1:4,1:4]= c  #here : works ad a from for one index to other
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
q=np.array([1,2,3,4])
##c=q xxxx
c=q.copy()
print(c)

[1 2 3 4]
